#ifndef APP_CONFIG_H_
#define APP_CONFIG_H_

#define HTTP_PORT 80
#define SETTING_HOLD_TIME 3000
#define LED_TIME_INTERVAL 500
#define SWITCH_TIMEOUT 3000
#define SIGNAL_IS_OPEN HIGH
#define SIGNAL_IS_CLOSE HIGH
#define LED_SIGNAL_IF_OPEN LOW
#define LED_SIGNAL_IF_CLOSE HIGH
#define PIN_RESET D1
#define SERIAL_BAUD_RATE 9600
#define JSON_BUFFER_LENGTH 1460

#define NORMAL_MODE 1
#define SERVER_MODE 2
#define ATTENDANCE_MODE 3
#define PREPARE_ATTENDANCE_MODE 4
#define CONNECT_MODULE 5
#define PREPARE_SCHEDULES_MODE 6

#endif